### ISSUE TITLE
Guile shebang is rejected due to \

### ISSUE THREAD

**Issue by aecepoglu** [eraserhd/parinfer-rust#100]
I have guile scripts I use as CLI programs which have shebangs like so:

```
#! /usr/local/bin/guile \
-e main -s
!#
(define (main args)
  (write args)
  (newline))
```

https://www.gnu.org/software/guile/manual/html_node/Command-Line-Handling.html

This syntax isn't supported by parinfer-rust because it doesn't like `\` in line ends.

Is this intended?

**Comment by eraserhd** [comment]
I definitely want to support this case.

It looks like we support lisp block comments starting with `#|` but not `#!`, and we don't have any special handling of the first two characters of the file.

In addition, Guile appears to be unique in ignoring up until a closing `!#`:

* Gambit ignores the line starting with `#!` if at the beginning of a file, except to look for a token indicating the file's sublanguage.
* Chicken ignores to end-of-line anywhere in the file it sees `#!` that is not one of `#!optional`, `#!key`, `#!rest`, and `#!eof`.
* Gerbil seems to ignore the first line if it starts with `#!`.

So, I propose:

* Ignore the first line always if the file starts with `#!`.
* Add a `--guile-shebang` option that ignores until `!#` (instead of newline) after the shebang.

And maybe:

* Add a `--language guile` option that selects scheme defaults but also enables `--guile-shebang` option.

**Comment by mnacamura** [comment]
Another example of multiline shebang in a Scheme implementation:
```
#!/bin/sh
:; exec gosh -- $0 "$@"
```
See [Gauche manual sec. 3.3](https://practical-scheme.net/gauche/man/gauche-refe/Writing-Scheme-scripts.html#Writing-Scheme-scripts).
