### ISSUE TITLE
[Kakoune] Can't completely undo certain changes

### ISSUE THREAD

**Issue by andreyorst** [eraserhd/parinfer-rust#74]
After some changes made by parinfer smart mode it is impossible to recover original file state. I'll add minimal example later

**Comment by andreyorst** [comment]
A minimal example:

```clojure
(def vaiv
    {:a 1
     :b 2})
```

Now use `<a-j>` on first line to join it with second line:

```clojure
(def vaiv {:a 1
           :b 2})
```

Try to undo:

```clojure
(def vaiv {:a 1}
     :b 2)
```

No further undo is possible without disabling parinfer

**Comment by Calum-J-I** [comment]
I have experienced the same problem. I will add that the unexpected behavior doesn't occur for all edits but any edit that triggers a parinfer change will cause this. For example deleting a line in the middle of a list is no problem
```lisp
["one"
 "two"
 "three"]
```
becoming
```lisp
;;2xd
["one"
 "three"]
```
is not a problem but this edit cannot be undone
```lisp
;;3xd
["one"
 "two"]
```
Additionally if you make multiple changes you cannot undo any of them unless they are insertions. If you do i<esc>i<esc>i<esc> and each insertion triggers a parinfer edit you can undo each change as expected with uuu however multiple deletions like xdxdxd will all be undone with a single u.

**Comment by eraserhd** [comment]
@andreyorst The current work-around is to do "2u" when you get stuck, and the problem is definitely that the parinfer change is separate, and so when you type "u", you undo parinfer's "fixup commit", and when parinfer retriggers it does the same thing again.

Vim has an "undojoin" command, which Kakoune does not have, that allows the Vim plugin to merge the edits into one.  There are different possible ways around this, one of which is to make parinfer somehow undo the user edit then add it back with the fixes.  This is actually not too hard... hrmm...
